secrets:
    - 1b222136-5875-4aac-ba84-b62ba1ab52c3
sources:
    - https://github.com/diamondburned/disblob
image: alpine/edge
packages:
    - go
environment:
    GOMAXPROCS: 4 # 8 files at once
artifacts:
    - disblob/style.css
tasks:
    - test: |
        cd disblob
        go test -v
    - main: |
        # go to the repository
        cd disblob
        # build the CSS
        go run . >> ./style.css
        # publish the style.css file
        go run ./cmd/webhooker ~/.webhook ./style.css
