secrets:
    - 51e2201d-4297-47c0-a61d-3fc61de728a2
sources:
    - https://github.com/diamondburned/disblob
    - https://github.com/C1710/blobmoji
image: alpine/edge
packages:
    - go
environment:
    WEBHOOK_ID: 729185757352165407
tasks:
    - main: |
        # go to the repository
        cd disblob
        # install the emoji repository
        mv ../blobmoji ./blobmoji
        # build the CSS
        go run . >> ./style.css
        # git describe command returns 0 if release, so we can upload the URL
        if git describe --exact-match --tags HEAD &> /dev/null; then
            echo "Release build, uploading style.css..."
            WEBHOOK_TOKEN=$(< ~/.webhook_token) go run ./cmd/webhooker ./style.css
        fi
