secrets:
    - 51e2201d-4297-47c0-a61d-3fc61de728a2
sources:
    - https://github.com/diamondburned/disblob
image: alpine/edge
packages:
    - go
environment:
    WEBHOOK_ID: 729185757352165407
artifacts:
    - disblob/style.css
tasks:
    - main: |
        # go to the repository
        cd disblob
        # build the CSS
        go run . >> ./style.css
        # publish the style.css file
        WEBHOOK_TOKEN=$(< ~/.webhook_token) go run ./cmd/webhooker ./style.css
